apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: stonecraft-datastore
  description: Catalog entities for Stonecraft-Datastore.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
