apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: stonecraft-datastore-apps
  description: Applications managed within the Stonecraft-Datastore monorepo.
spec:
  targets:
    - ./catalog/*.yaml
    - ./catalog/**/*.yaml
